version: '3'

services:
  client:
    container_name: client
    build: ./client
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - server
    links:
      - server

  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
    restart: unless-stopped